# Configuration for GitHub Pages
title: Brave New World
description: A world beyond this planet
baseurl: "/BraveNewWorld"
url: "https://Madeadezign864.github.io"
theme: minima
markdown: kramdown